#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Mar  3 11:35:57 2009

import wx

# begin wxGlade: extracode
#from shell_frame import *
from IPython.gui.wx.ipython_view import IPShellWidget
# end wxGlade


class wxRTFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxRTFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.rtframe_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Ejecutar", "", wx.ITEM_NORMAL)
        self.rtframe_menubar.Append(wxglade_tmp_menu, "Archivo")
        self.SetMenuBar(self.rtframe_menubar)

        # Menu Bar end
        self.rtframe_statusbar = self.CreateStatusBar(1, 0)
        self.rtshell = IPShellWidget(self)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.evt_run_file, id=-1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxRTFrame.__set_properties
        self.SetTitle("Trazo de Rayos - Consola")
        self.rtframe_statusbar.SetStatusWidths([-1])
        # statusbar fields
        rtframe_statusbar_fields = [""]
        for i in range(len(rtframe_statusbar_fields)):
            self.rtframe_statusbar.SetStatusText(rtframe_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxRTFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.rtshell, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def evt_run_file(self, event): # wxGlade: wxRTFrame.<event_handler>
        print "Event handler `evt_run_file' not implemented!"
        event.Skip()

# end of class wxRTFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame1 = wxRTFrame(None, -1, "")
    app.SetTopWindow(frame1)
    frame1.Show()
    app.MainLoop()
