name: Build and Publish Wheel

on:
  push:
    #tags: 'v*.*.*'

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Set up Build Environment Variables
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            # Install Eigen inside the Linux build container
            echo "CIBW_BEFORE_ALL_LINUX=yum install -y eigen3-devel && export EIGEN3_INCLUDE_DIR=/usr/include/eigen3" >> $GITHUB_ENV
            echo "CIBW_ENVIRONMENT_LINUX=EIGEN3_INCLUDE_DIR=/usr/include/eigen3" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            # Install Eigen using Homebrew
            brew update
            brew install eigen
            EIGEN_DIR=$(brew --prefix eigen)/include/eigen3
            echo "EIGEN3_INCLUDE_DIR=$EIGEN_DIR" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            # Install Eigen for Windows
            choco install -y 7zip
            curl -L -o eigen.zip https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
            "C:\Program Files\7-Zip\7z.exe" x eigen.zip -oeigen
            EIGEN_DIR=$(cygpath -m "$PWD")/eigen/eigen-3.4.0
            echo "EIGEN3_INCLUDE_DIR=$EIGEN_DIR" >> $GITHUB_ENV
          fi

      - name: Build Wheels
        run: cibuildwheel --output-dir wheelhouse

      - name: Upload Wheels as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse-${{ runner.os }}-py${{ matrix.python-version }}
          path: wheelhouse

      - name: Upload Wheels to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse
