name: Build and Publish Wheel

on:
  push:
    # tags: 'v*.*.*'

jobs:
  build_wheel:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python${{ matrix.python-version }}-dev libeigen3-dev
          pip install --upgrade pip setuptools wheel

      - name: Install Cython
        run: pip install cython

      - name: Build Wheel
        env:
          EIGEN3_INCLUDE_DIR: /usr/include/eigen3
        run: |
          python setup.py bdist_wheel

      - name: Upload Wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist
