name: Build and Publish Wheel

on:
  push:
    tags: 'v*.*.*'

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      # Set up Build Dependencies and Environment Variables
      - name: Set up Build Dependencies and Environment Variables
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            # Commands to run inside the build containers to install Eigen
            echo "CIBW_BEFORE_ALL_LINUX<<EOF" >> $GITHUB_ENV
            echo "yum install -y eigen3-devel && export EIGEN3_INCLUDE_DIR=/usr/include/eigen3" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

            echo "CIBW_ENVIRONMENT_LINUX<<EOF" >> $GITHUB_ENV
            echo "EIGEN3_INCLUDE_DIR=/usr/include/eigen3" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install eigen
            EIGEN_DIR=$(brew --prefix eigen)/include/eigen3
            echo "EIGEN3_INCLUDE_DIR=$EIGEN_DIR" >> $GITHUB_ENV
            # Skip building for Python 3.8, 3.9, and 3.10 on macOS
            echo "CIBW_SKIP=cp38-macosx_* cp39-macosx_* cp310-macosx_*" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install -y 7zip
            curl -L -o eigen.zip https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
            "C:\Program Files\7-Zip\7z.exe" x eigen.zip -oeigen
            EIGEN_DIR=$(cygpath -m "$PWD")/eigen/eigen-3.4.0
            echo "EIGEN3_INCLUDE_DIR=$EIGEN_DIR" >> $GITHUB_ENV
          fi

      # Build Wheels using cibuildwheel
      - name: Build Wheels
        run: cibuildwheel --output-dir wheelhouse

      # Upload Wheels as Artifacts
      - name: Upload Wheels as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse-${{ runner.os }}
          path: wheelhouse

      # Upload Wheels to PyPI
      - name: Upload Wheels to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse
