name: Build and Publish Wheels

on:
  push:
    # tags: 'v*.*.*'

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.12.1

      # Install Eigen3 on Ubuntu
      - name: Install Eigen3 on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev

      # Install Eigen3 on macOS
      - name: Install Eigen3 on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install eigen

      # Install Eigen3 on Windows
      - name: Install Eigen3 on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri 'https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip' -OutFile 'eigen.zip'
          Expand-Archive -Path 'eigen.zip' -DestinationPath 'eigen'
          echo "EIGEN3_INCLUDE_DIR=${{ github.workspace }}\eigen\eigen-3.4.0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build Wheels
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
          CIBW_BEFORE_BUILD: pip install cython
          CIBW_ENVIRONMENT: EIGEN3_INCLUDE_DIR=$EIGEN3_INCLUDE_DIR
        run: python -m cibuildwheel --output-dir wheelhouse

      #- name: Upload Wheels to PyPI
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    password: ${{ secrets.PYPI_API_TOKEN }}
      #    packages_dir: wheelhouse
