name: Build Package

on: push

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        pip install Cython==0.29.32 --config-settings="--install-option=--no-cython-compile"
        pip install cibuildwheel
        PYTHON_VERSION=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
        # Install different numpy versions based on the Python version
        case $PYTHON_VERSION in
          3.8)
            pip install numpy==1.19.3 # Example version for Python 3.8
            ;;
          3.9)
            pip install numpy==1.26.2 # Example version for Python 3.9
            ;;
          3.10)
            pip install numpy==1.26.2 # Example version for Python 3.10
            ;;
          3.11)
            pip install numpy==1.24.2 # Assuming the latest numpy is compatible with Python 3.11
            ;;
          *)
            echo "Unsupported Python version: $PYTHON_VERSION"
            exit 1
            ;;
        esac
        
    - name: Build sdist
      run: python setup.py sdist --formats=zip
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir dist/
      env:
        CIBW_BUILD: "cp38* cp39* cp310* cp311*"
        CIBW_SKIP: "*_i686 *musllinux* pp* *win32"
    - name: Upload Distributions
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist/*.whl
          dist/*.tar.gz
          dist/*.zip
        retention-days: 7

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
