name: Build Package

on: push

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        pip install Cython==0.29.32 --config-settings="--install-option=--no-cython-compile"
        pip install cibuildwheel
        
        python -c "import sys; \
        py_ver = sys.version_info; \
        numpy_version = 'numpy==1.19.3' if py_ver.minor == 8 else \
                        'numpy==1.26.2' if py_ver.minor == 9 else \
                        'numpy==1.26.2' if py_ver.minor == 10 else \
                        'numpy==1.24.2'; \
        print(numpy_version); \
        sys.exit(0 if py_ver.minor in [8, 9, 10, 11] else 1); \
        " > numpy_version.txt
        pip install -r numpy_version.txt
        rm numpy_version.txt

    - name: Build sdist
      run: python setup.py sdist --formats=zip
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir dist/
            
    - name: Upload Distributions
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist/*.whl
          dist/*.tar.gz
          dist/*.zip
        retention-days: 7

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
