name: Build and Publish Wheels

on:
  push:
    #tags: 'v*.*.*'

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Builds for all available Python 3 versions

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.12.1

      - name: Install Dependencies and Build Wheels
        env:
          CIBW_BEFORE_BUILD: pip install cython
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libeigen3-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install eigen
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install eigen
            # Ensure choco is in the PATH
            echo "::add-path::C:\ProgramData\chocolatey\bin"
          fi
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload Wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse
